markdown: redcarpet
baseurl: ""
title: Valentin Joly

plugins:
  - jekyll/scholar

scholar:
  style: /_bibliography/vjoly.csl
  sort_by: authors, date
  bibliography_list_tag: ol


navbar_pages:
  - research.html
  - experience.html
  - publications.html
  - awards.html

google_analytics: UA-122333490-1

languages: [en, fr, es, it]

image_dir: "/images/"
paper_dir: "/papers/"
