baseurl: ""
title: Valentin Joly
url: "https://vjoly.net"

plugins:
  - jekyll/scholar
  - jekyll-seo-tag
  - jekyll-sitemap

scholar:
  style: /_bibliography/vjoly.csl
  bibliography_list_tag: ol

navbar_pages:
  - research.html
  - experience.html
  - publications.html
  - awards.html
  - blog.html

google_analytics: UA-122333490-1

languages: [en, fr, es, it, eo]

image_dir: "/images/"
docs_dir: "/docs/"

doi_url_prefix: "https://doi.org/"
pubmed_url_prefix: "https://www.ncbi.nlm.nih.gov/pubmed/"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - images/raw/

