baseurl: ""
title: Valentin Joly
url: "http://vjoly.net"

plugins:
  - jekyll/scholar
  - jekyll-seo-tag
  - jekyll-sitemap

scholar:
  style: /_bibliography/vjoly.csl
  sort_by: authors, date
  bibliography_list_tag: ol

navbar_pages:
  - research.html
  - experience.html
  - publications.html
  - awards.html
  - blog.html

google_analytics: UA-122333490-1

languages: [en, fr, es, it]

image_dir: "/images/"
paper_dir: "/papers/"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - images/raw/

